### ISSUE TITLE
Why don't we use ROS for payload code?

### ISSUE THREAD

**Issue by kevtan** [stanford-ssi/sequoia-software#8]
@lgnashold @Timvrakas Why do we not use something like [ROS](https://www.ros.org/) for our payload code? I looked at the README and the architecture we've set up is exactly the ROS architecture, with nodes (you guys are calling them microservices) and a central parameter server (you guys are using a Redis message passing middle man). ROS is an industry standard, at least in the academic community, and could be a valuable framework to learn for members.

**Comment by lgnashold** [comment]
@austrian-code-wizard

**Comment by kevtan** [comment]
@lgnashold @austrian-code-wizard @polygnomial Another benefit of using ROS is that we don't have to implement our own state machine code. ROS has a way of doing this (called SMACH) that also gives us a GUI in addition to some base classes.

**Comment by kevtan** [comment]
I don't think implementing our own state machine class is a good idea because it has the potential to be very buggy without extensive testing. Instead, I think we should use something like `pysm` and if we encounter any bugs we can contribute it back to that project. The better solution in general, however, is to change to the ROS framework so we can use [SMACH](https://wiki.ros.org/smach).

**Comment by Timvrakas** [comment]
I haven't used ROS, but I have heard of it beimg used. Keep in mind that our radio link will be very restrited, so if ROS is expecting a wifi link or something, it may have limitations.
Also, not sure how much flight logic will be on the Pi. If the Pi is just image processing compute, it might not be worth changing.

**Comment by polygnomial** [comment]
The Pi will be running plenty of the GNC code (star tracking, etc).

**Comment by polygnomial** [comment]
I'm also confused--SMACH says it's independent of ROS, with a Python interface. I'm guessing that the benefit of using that is better organization, while it seems like the benefit of Rust or C++ with ROS bindings is efficiency.

**Comment by austrian-code-wizard** [comment]
From what I've read it seems like at the core ROS is a middleware providing pub / sub message queues, request / response procedures, and a key value store + a lot of robotics specific features. Redis does cover the first three points as well and from what I see, we don't need most of the other features they have. How is ROS performance-wise compared to Redis? Generally, I think in terms of the philosophy of this is build, the aim is to get a little bit away from robotics-specific tools in general and utilize technologies that are more general. Let's talk about it during the meeting tonight @kevtan , I'd love to learn more about it!

**Comment by kevtan** [comment]
@polygnomial With ROS, we can pick which parts of the framework we want to use. I'm sure there's a way you can jerryrig SMACH without the rest of the framework but, as you said, if we use more of the ROS framework we have better organization.

@austrian-code-wizard I think you're concern about performance is totally valid and I had to do some more research as that whether or not we might be resource-constrained but my overwhelming conclusion is no. I've prepared a slideshow https://docs.google.com/presentation/d/121OcXi6PzQAwCJmvzk_nqVCogbJO31tSsmLX9t5s03g/edit?usp=sharing for tonight. It's pretty minimal as I plan on talking through everyone more in person, but feel free to check it out.
